server:
  port: 8888
spring:
  application:
    name: config-center
  cloud:
    config:
      server:
        git:
          uri: https://git.oschina.net/letmegogoing_admin/cloud-config-repo
          username: hyx199170@gmail.com
          password: qwe12356
    zookeeper:
      connect-string: 106.12.97.129:2181