package com.cloud.provider.bean;

import java.io.Serializable;
import java.util.Date;

public class FaceCaptureHistory implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column face_capture_history.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column face_capture_history.camera_id
     *
     * @mbg.generated
     */
    private String cameraId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column face_capture_history.face_id
     *
     * @mbg.generated
     */
    private String faceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column face_capture_history.face_time
     *
     * @mbg.generated
     */
    private Date faceTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column face_capture_history.face_fsimilarity
     *
     * @mbg.generated
     */
    private Float faceFsimilarity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column face_capture_history.status
     *
     * @mbg.generated
     */
    private Boolean status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column face_capture_history.obs_id
     *
     * @mbg.generated
     */
    private Long obsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column face_capture_history.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column face_capture_history.sex
     *
     * @mbg.generated
     */
    private Boolean sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column face_capture_history.age
     *
     * @mbg.generated
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column face_capture_history.is_glasses
     *
     * @mbg.generated
     */
    private Boolean isGlasses;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column face_capture_history.is_smile
     *
     * @mbg.generated
     */
    private Boolean isSmile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column face_capture_history.is_hat
     *
     * @mbg.generated
     */
    private Boolean isHat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table face_capture_history
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column face_capture_history.id
     *
     * @return the value of face_capture_history.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column face_capture_history.id
     *
     * @param id the value for face_capture_history.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column face_capture_history.camera_id
     *
     * @return the value of face_capture_history.camera_id
     *
     * @mbg.generated
     */
    public String getCameraId() {
        return cameraId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column face_capture_history.camera_id
     *
     * @param cameraId the value for face_capture_history.camera_id
     *
     * @mbg.generated
     */
    public void setCameraId(String cameraId) {
        this.cameraId = cameraId == null ? null : cameraId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column face_capture_history.face_id
     *
     * @return the value of face_capture_history.face_id
     *
     * @mbg.generated
     */
    public String getFaceId() {
        return faceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column face_capture_history.face_id
     *
     * @param faceId the value for face_capture_history.face_id
     *
     * @mbg.generated
     */
    public void setFaceId(String faceId) {
        this.faceId = faceId == null ? null : faceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column face_capture_history.face_time
     *
     * @return the value of face_capture_history.face_time
     *
     * @mbg.generated
     */
    public Date getFaceTime() {
        return faceTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column face_capture_history.face_time
     *
     * @param faceTime the value for face_capture_history.face_time
     *
     * @mbg.generated
     */
    public void setFaceTime(Date faceTime) {
        this.faceTime = faceTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column face_capture_history.face_fsimilarity
     *
     * @return the value of face_capture_history.face_fsimilarity
     *
     * @mbg.generated
     */
    public Float getFaceFsimilarity() {
        return faceFsimilarity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column face_capture_history.face_fsimilarity
     *
     * @param faceFsimilarity the value for face_capture_history.face_fsimilarity
     *
     * @mbg.generated
     */
    public void setFaceFsimilarity(Float faceFsimilarity) {
        this.faceFsimilarity = faceFsimilarity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column face_capture_history.status
     *
     * @return the value of face_capture_history.status
     *
     * @mbg.generated
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column face_capture_history.status
     *
     * @param status the value for face_capture_history.status
     *
     * @mbg.generated
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column face_capture_history.obs_id
     *
     * @return the value of face_capture_history.obs_id
     *
     * @mbg.generated
     */
    public Long getObsId() {
        return obsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column face_capture_history.obs_id
     *
     * @param obsId the value for face_capture_history.obs_id
     *
     * @mbg.generated
     */
    public void setObsId(Long obsId) {
        this.obsId = obsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column face_capture_history.name
     *
     * @return the value of face_capture_history.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column face_capture_history.name
     *
     * @param name the value for face_capture_history.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column face_capture_history.sex
     *
     * @return the value of face_capture_history.sex
     *
     * @mbg.generated
     */
    public Boolean getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column face_capture_history.sex
     *
     * @param sex the value for face_capture_history.sex
     *
     * @mbg.generated
     */
    public void setSex(Boolean sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column face_capture_history.age
     *
     * @return the value of face_capture_history.age
     *
     * @mbg.generated
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column face_capture_history.age
     *
     * @param age the value for face_capture_history.age
     *
     * @mbg.generated
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column face_capture_history.is_glasses
     *
     * @return the value of face_capture_history.is_glasses
     *
     * @mbg.generated
     */
    public Boolean getIsGlasses() {
        return isGlasses;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column face_capture_history.is_glasses
     *
     * @param isGlasses the value for face_capture_history.is_glasses
     *
     * @mbg.generated
     */
    public void setIsGlasses(Boolean isGlasses) {
        this.isGlasses = isGlasses;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column face_capture_history.is_smile
     *
     * @return the value of face_capture_history.is_smile
     *
     * @mbg.generated
     */
    public Boolean getIsSmile() {
        return isSmile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column face_capture_history.is_smile
     *
     * @param isSmile the value for face_capture_history.is_smile
     *
     * @mbg.generated
     */
    public void setIsSmile(Boolean isSmile) {
        this.isSmile = isSmile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column face_capture_history.is_hat
     *
     * @return the value of face_capture_history.is_hat
     *
     * @mbg.generated
     */
    public Boolean getIsHat() {
        return isHat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column face_capture_history.is_hat
     *
     * @param isHat the value for face_capture_history.is_hat
     *
     * @mbg.generated
     */
    public void setIsHat(Boolean isHat) {
        this.isHat = isHat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table face_capture_history
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        FaceCaptureHistory other = (FaceCaptureHistory) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getCameraId() == null ? other.getCameraId() == null : this.getCameraId().equals(other.getCameraId()))
            && (this.getFaceId() == null ? other.getFaceId() == null : this.getFaceId().equals(other.getFaceId()))
            && (this.getFaceTime() == null ? other.getFaceTime() == null : this.getFaceTime().equals(other.getFaceTime()))
            && (this.getFaceFsimilarity() == null ? other.getFaceFsimilarity() == null : this.getFaceFsimilarity().equals(other.getFaceFsimilarity()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getObsId() == null ? other.getObsId() == null : this.getObsId().equals(other.getObsId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getSex() == null ? other.getSex() == null : this.getSex().equals(other.getSex()))
            && (this.getAge() == null ? other.getAge() == null : this.getAge().equals(other.getAge()))
            && (this.getIsGlasses() == null ? other.getIsGlasses() == null : this.getIsGlasses().equals(other.getIsGlasses()))
            && (this.getIsSmile() == null ? other.getIsSmile() == null : this.getIsSmile().equals(other.getIsSmile()))
            && (this.getIsHat() == null ? other.getIsHat() == null : this.getIsHat().equals(other.getIsHat()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table face_capture_history
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getCameraId() == null) ? 0 : getCameraId().hashCode());
        result = prime * result + ((getFaceId() == null) ? 0 : getFaceId().hashCode());
        result = prime * result + ((getFaceTime() == null) ? 0 : getFaceTime().hashCode());
        result = prime * result + ((getFaceFsimilarity() == null) ? 0 : getFaceFsimilarity().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getObsId() == null) ? 0 : getObsId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getSex() == null) ? 0 : getSex().hashCode());
        result = prime * result + ((getAge() == null) ? 0 : getAge().hashCode());
        result = prime * result + ((getIsGlasses() == null) ? 0 : getIsGlasses().hashCode());
        result = prime * result + ((getIsSmile() == null) ? 0 : getIsSmile().hashCode());
        result = prime * result + ((getIsHat() == null) ? 0 : getIsHat().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table face_capture_history
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", cameraId=").append(cameraId);
        sb.append(", faceId=").append(faceId);
        sb.append(", faceTime=").append(faceTime);
        sb.append(", faceFsimilarity=").append(faceFsimilarity);
        sb.append(", status=").append(status);
        sb.append(", obsId=").append(obsId);
        sb.append(", name=").append(name);
        sb.append(", sex=").append(sex);
        sb.append(", age=").append(age);
        sb.append(", isGlasses=").append(isGlasses);
        sb.append(", isSmile=").append(isSmile);
        sb.append(", isHat=").append(isHat);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}