package com.cloud.provider.dao;

import com.cloud.provider.bean.FaceDetail;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface FaceDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table face_detail
     *
     * @mbg.generated
     */
    int insert(FaceDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table face_detail
     *
     * @mbg.generated
     */
    int insertSelective(FaceDetail record);
}