package com.cloud.provider.dao;

import com.cloud.provider.bean.FaceSet;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface FaceSetMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table face_set
     *
     * @mbg.generated
     */
    int insert(FaceSet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table face_set
     *
     * @mbg.generated
     */
    int insertSelective(FaceSet record);
}