package com.cloud.provider.dao;

import com.cloud.provider.bean.FaceDetail;

public interface FaceDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table face_detail
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table face_detail
     *
     * @mbg.generated
     */
    int insert(FaceDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table face_detail
     *
     * @mbg.generated
     */
    int insertSelective(FaceDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table face_detail
     *
     * @mbg.generated
     */
    FaceDetail selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table face_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FaceDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table face_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FaceDetail record);
}