package com.cloud.provider.dao;

import com.cloud.provider.bean.FaceSet;

public interface FaceSetMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table face_set
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table face_set
     *
     * @mbg.generated
     */
    int insert(FaceSet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table face_set
     *
     * @mbg.generated
     */
    int insertSelective(FaceSet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table face_set
     *
     * @mbg.generated
     */
    FaceSet selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table face_set
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FaceSet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table face_set
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FaceSet record);
}